# Generated by Django 5.1.6 on 2025-03-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('isAvailable', models.BooleanField()),
            ],
        ),
    ]
